name: hero_kids
description: "Hero Kids - Your intelligent assistant for creative tasks."

publish_to: 'none'

version: 2.0.0+2

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.5.1
  image_picker: ^1.0.4
  google_sign_in: ^6.1.5
  flutter_facebook_auth: ^6.0.3
  flutter_svg: ^2.0.7
  http: ^1.5.0
  video_player: ^2.8.2
  chewie: ^1.7.5
  google_fonts: ^6.1.0
  carousel_slider: ^5.1.1
  font_awesome_flutter: ^10.9.1
  google_generative_ai: ^0.4.6
  cached_network_image: ^3.3.1
  shared_preferences: ^2.2.2
  flutter_native_splash: ^2.3.10
  flutter_launcher_icons: ^0.14.1
  go_router: ^14.6.2
  fluttertoast: ^8.2.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:


  uses-material-design: true
  assets:
    - assets/translations/
    - assets/app_icon.png
    - assets/w copy.png
    - assets/s1 copy.jpg
    - assets/s2 copy.jpg
    - assets/shuffle1 copy.jpeg
    - assets/shuffle2 copy.jpeg
    - assets/bn copy.png
    - assets/11 copy.png
    - assets/22 copy.png
    - assets/33 copy.png
    - assets/44444 copy.png
    - assets/4444 copy.png
    - assets/g copy.png
    - assets/ggggggggg copy.png
    - assets/E1 copy.png
    - assets/E2 copy.png
    - assets/E3 copy.png
    - assets/1t copy.png
    - assets/22t copy.png
    - assets/3t copy.png
    - assets/1c copy.png
    - assets/2c copy.png
    - assets/33c copy.png
    - assets/google copy.png
    - assets/Group.png
    - assets/googleee copy.png
    - assets/1c copy.png
    - assets/2c copy.png
    - assets/33c copy.png
    - assets/pw copy.png
    - assets/banner copy.png
    - assets/video-preview.mp4
    - assets/pink-gradient copy.svg
    - assets/flags/
    - assets/boyui copy.png
    - assets/girlui copy.png
    - assets/vd.mp4
    - assets/logo.png
    - assets/logo_no_alpha.png
    - assets/logs copy.png
    - assets/logs.png
    - assets/mm.png
    - assets/ww2.png
    - assets/ww3.png
    - assets/T1.png
    - assets/T2.png
    - assets/T3.png
    - assets/a1.png
    - assets/a2.png
    - assets/a3.png
    - assets/a4.png

flutter_native_splash:
  color: "#ffffff"
  image: assets/logs copy.png
  android: true
  ios: true
  web: true
  fullscreen: true
  android_gravity: center
  ios_content_mode: center
  android_12:
    image: assets/logs copy.png
    color: "#ffffff"
    # branding: assets/logs copy.png
    # branding_mode: bottom

flutter_launcher_icons:
  android: true
  ios: true
  web:
    generate: true
    image_path: "assets/app_icon.png"
    background_color: "#ffffff"
    theme_color: "#6B46C1"
  image_path: "assets/app_icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/app_icon.png"
